import { SessionProvider } from '@/components/SessionProvider';
import SideBar from '@/components/SideBar';
import { getServerSession } from 'next-auth';
import '@/styles/globals.css';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Login from '@/components/Login';
import ClientProvider from '@/components/ClientProvider';

export const metadata = {
  title: 'ChatGTP Awesome',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  // console.log(session);
  document.documentElement.style.setProperty("--vh", window.innerHeight * 0.01 + 'px');
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className='absolute inset-0 flex'>
              <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
                <SideBar />
              </div>
              {/*ClientProvider - Notification because toast notification need client side, but this is server side */}
              <ClientProvider />
              <div className='bg-[#343541] flex-1'>
                {children}
              </div>

            </div>
          )}

        </SessionProvider>
      </body >
    </html >
  )
}
